// ============================================================
// Website Builder Pro — CSS Engine
// ============================================================

import type { ElementStyles, SiteTheme, ElementNode, SectionNode, RowNode } from './types';

/* ========== Style Object ↔ CSS ========== */

export function camelToKebab(str: string): string {
  return str.replace(/[A-Z]/g, m => `-${m.toLowerCase()}`);
}

/** Convert ElementStyles to inline CSS string */
export function stylesToCSS(styles: ElementStyles): string {
  return Object.entries(styles)
    .filter(([, v]) => v !== undefined && v !== '')
    .map(([k, v]) => `${camelToKebab(k)}: ${v}`)
    .join('; ');
}

/** Convert ElementStyles to React CSSProperties */
export function stylesToReact(styles: ElementStyles): React.CSSProperties {
  const result: Record<string, string> = {};
  for (const [k, v] of Object.entries(styles)) {
    if (v !== undefined && v !== '') {
      result[k] = v;
    }
  }
  return result as React.CSSProperties;
}

/* ========== Theme CSS Variables ========== */

export function generateThemeCSS(theme: SiteTheme): string {
  return `
/* Light theme */
[data-theme="light"] {
  --site-bg: ${theme.light.bg};
  --site-text: ${theme.light.text};
  --site-surface: ${theme.light.surface};
  --site-border: ${theme.light.border};
  --site-accent: ${theme.accent};
  --font-heading: ${getFontFamily(theme.fonts.heading)};
  --font-body: ${getFontFamily(theme.fonts.body)};
  --radius: ${theme.borderRadius};
  color-scheme: light;
}

/* Dark theme */
[data-theme="dark"] {
  --site-bg: ${theme.dark.bg};
  --site-text: ${theme.dark.text};
  --site-surface: ${theme.dark.surface};
  --site-border: ${theme.dark.border};
  --site-accent: ${theme.accent};
  --font-heading: ${getFontFamily(theme.fonts.heading)};
  --font-body: ${getFontFamily(theme.fonts.body)};
  --radius: ${theme.borderRadius};
  color-scheme: dark;
}
`;
}

function getFontFamily(name: string): string {
  const map: Record<string, string> = {
    'Inter': "'Inter', sans-serif",
    'DM Sans': "'DM Sans', sans-serif",
    'Outfit': "'Outfit', sans-serif",
    'Plus Jakarta Sans': "'Plus Jakarta Sans', sans-serif",
    'Poppins': "'Poppins', sans-serif",
    'Roboto': "'Roboto', sans-serif",
    'Open Sans': "'Open Sans', sans-serif",
    'Montserrat': "'Montserrat', sans-serif",
    'Lato': "'Lato', sans-serif",
    'Space Grotesk': "'Space Grotesk', sans-serif",
    'Playfair Display': "'Playfair Display', serif",
    'Merriweather': "'Merriweather', serif",
    'Georgia': "Georgia, serif",
    'Lora': "'Lora', serif",
    'JetBrains Mono': "'JetBrains Mono', monospace",
    'Fira Code': "'Fira Code', monospace",
    'System UI': "system-ui, -apple-system, sans-serif",
  };
  return map[name] ?? `'${name}', sans-serif`;
}

/* ========== Hover CSS for Export ========== */

export function generateElementHoverCSS(elementId: string, hoverStyles: ElementStyles): string {
  const css = stylesToCSS(hoverStyles);
  if (!css) return '';
  return `[data-id="${elementId}"]:hover { ${css}; }`;
}

/* ========== Base CSS for Exported Sites ========== */

export function generateBaseCSS(theme: SiteTheme): string {
  return `/* Generated by Website Builder Pro */
/* Reset */
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
html { scroll-behavior: smooth; }
body {
  font-family: var(--font-body);
  background: var(--site-bg);
  color: var(--site-text);
  line-height: 1.6;
  min-height: 100vh;
  -webkit-font-smoothing: antialiased;
}
img { max-width: 100%; height: auto; display: block; }
a { color: inherit; text-decoration: none; }
button { cursor: pointer; border: none; background: none; font: inherit; }
ul, ol { list-style-position: inside; }

${generateThemeCSS(theme)}

/* Layout */
.site-header {
  position: sticky;
  top: 0;
  z-index: 100;
  background: var(--site-bg);
  backdrop-filter: blur(12px);
}
.site-footer {
  background: var(--site-surface);
}
.wb-section {
  width: 100%;
}
.wb-section-inner {
  max-width: 1200px;
  margin: 0 auto;
  padding-left: 1.5rem;
  padding-right: 1.5rem;
}
.wb-section.full-bleed .wb-section-inner {
  max-width: 100%;
  padding-left: 0;
  padding-right: 0;
}

/* Grid */
.wb-row {
  display: grid;
  grid-template-columns: repeat(12, 1fr);
  gap: 1.5rem;
  width: 100%;
}
.wb-col { min-width: 0; }
.wb-col-1 { grid-column: span 1; }
.wb-col-2 { grid-column: span 2; }
.wb-col-3 { grid-column: span 3; }
.wb-col-4 { grid-column: span 4; }
.wb-col-5 { grid-column: span 5; }
.wb-col-6 { grid-column: span 6; }
.wb-col-7 { grid-column: span 7; }
.wb-col-8 { grid-column: span 8; }
.wb-col-9 { grid-column: span 9; }
.wb-col-10 { grid-column: span 10; }
.wb-col-11 { grid-column: span 11; }
.wb-col-12 { grid-column: span 12; }

/* Elements */
h1, h2, h3, h4, h5, h6 {
  font-family: var(--font-heading);
  line-height: 1.2;
}
.wb-btn {
  display: inline-block;
  cursor: pointer;
  transition: all 0.2s ease;
}
.wb-btn:hover { opacity: 0.9; }
.wb-icon { display: inline-block; }
.wb-video-wrapper {
  position: relative;
  width: 100%;
}
.wb-video-wrapper iframe {
  width: 100%;
  height: 100%;
  border: none;
}
.wb-map iframe {
  width: 100%;
  height: 100%;
  border: none;
}
.wb-embed iframe {
  width: 100%;
  height: 100%;
  border: none;
}
.wb-code {
  overflow-x: auto;
}
.wb-social-links {
  display: flex;
  gap: 1rem;
  align-items: center;
}
.wb-social-links a {
  transition: opacity 0.2s;
}
.wb-social-links a:hover {
  opacity: 0.7;
}

/* Forms */
.wb-form input,
.wb-form textarea,
.wb-form select {
  width: 100%;
  padding: 0.75rem 1rem;
  border: 1px solid var(--site-border);
  border-radius: var(--radius);
  background: var(--site-bg);
  color: var(--site-text);
  font-family: var(--font-body);
  font-size: 1rem;
  transition: border-color 0.2s;
}
.wb-form input:focus,
.wb-form textarea:focus,
.wb-form select:focus {
  outline: none;
  border-color: var(--site-accent);
}
.wb-form label {
  display: block;
  margin-bottom: 0.375rem;
  font-weight: 500;
  font-size: 0.875rem;
}
.wb-form .form-group {
  display: flex;
  flex-direction: column;
}
.wb-form button[type="submit"] {
  padding: 0.75rem 2rem;
  background: var(--site-accent);
  color: #fff;
  border: none;
  border-radius: var(--radius);
  font-weight: 600;
  font-size: 1rem;
  cursor: pointer;
  transition: opacity 0.2s;
}
.wb-form button[type="submit"]:hover {
  opacity: 0.9;
}

/* Theme Toggle */
.theme-toggle {
  position: fixed;
  bottom: 1.5rem;
  right: 1.5rem;
  width: 44px;
  height: 44px;
  border-radius: 50%;
  background: var(--site-surface);
  border: 1px solid var(--site-border);
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  font-size: 1.25rem;
  z-index: 1000;
  transition: all 0.2s;
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
}
.theme-toggle:hover {
  transform: scale(1.1);
}

/* Responsive */
@media (max-width: 768px) {
  .wb-row {
    grid-template-columns: 1fr;
    gap: 1rem;
  }
  .wb-col-1, .wb-col-2, .wb-col-3, .wb-col-4,
  .wb-col-5, .wb-col-6, .wb-col-7, .wb-col-8,
  .wb-col-9, .wb-col-10, .wb-col-11, .wb-col-12 {
    grid-column: span 1;
  }
  .wb-section-inner {
    padding-left: 1rem;
    padding-right: 1rem;
  }
  h1 { font-size: 2rem !important; }
  h2 { font-size: 1.5rem !important; }
}

/* Animations */
@keyframes fadeInUp {
  from { opacity: 0; transform: translateY(20px); }
  to { opacity: 1; transform: translateY(0); }
}
@keyframes fadeIn {
  from { opacity: 0; }
  to { opacity: 1; }
}
.animate-fade-in-up { animation: fadeInUp 0.6s ease forwards; }
.animate-fade-in { animation: fadeIn 0.4s ease forwards; }
`;
}

/* ========== Google Fonts URL ========== */

export function getGoogleFontsUrl(theme: SiteTheme): string {
  const fonts = new Set<string>();
  const addFont = (name: string) => {
    const map: Record<string, string> = {
      'Inter': 'Inter:wght@300;400;500;600;700;800;900',
      'DM Sans': 'DM+Sans:wght@400;500;600;700',
      'Outfit': 'Outfit:wght@300;400;500;600;700;800',
      'Plus Jakarta Sans': 'Plus+Jakarta+Sans:wght@400;500;600;700;800',
      'Poppins': 'Poppins:wght@300;400;500;600;700',
      'Roboto': 'Roboto:wght@300;400;500;700',
      'Open Sans': 'Open+Sans:wght@300;400;600;700',
      'Montserrat': 'Montserrat:wght@400;500;600;700;800',
      'Lato': 'Lato:wght@300;400;700',
      'Space Grotesk': 'Space+Grotesk:wght@400;500;600;700',
      'Playfair Display': 'Playfair+Display:wght@400;500;600;700;800',
      'Merriweather': 'Merriweather:wght@300;400;700',
      'Lora': 'Lora:wght@400;500;600;700',
      'JetBrains Mono': 'JetBrains+Mono:wght@400;500;700',
      'Fira Code': 'Fira+Code:wght@400;500;700',
    };
    if (map[name]) fonts.add(map[name]);
  };
  addFont(theme.fonts.heading);
  addFont(theme.fonts.body);
  if (fonts.size === 0) return '';
  return `https://fonts.googleapis.com/css2?${[...fonts].map(f => `family=${f}`).join('&')}&display=swap`;
}

/* ========== Collect All Hover Styles from a Page ========== */

export function collectHoverCSS(sections: SectionNode[]): string {
  const rules: string[] = [];
  const walk = (elements: ElementNode[]) => {
    for (const el of elements) {
      const hover = generateElementHoverCSS(el.id, el.hoverStyles);
      if (hover) rules.push(hover);
      if (el.children.length > 0) walk(el.children);
    }
  };
  for (const sec of sections) {
    for (const row of sec.rows) {
      for (const col of row.columns) {
        walk(col.elements);
      }
    }
  }
  return rules.join('\n');
}
